---
title: "Solutions exercises"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
opts_chunk$set(
  echo = TRUE
)
opts_knit$set(root.dir = here::here())
```

```{r}
# packages
library(targets)
library(here)
```

# Challenge 1
## Create targets pipeline

```{r}
script <- here::here("source", "bird_analysis_pipeline", "_targets.R")
store <- here::here("source", "bird_analysis_pipeline", "_targets")
```

To set up the targets pipeline, the following code was used:

```
use_targets(
  script = script
)
```

We run the pipeline:

```{r}
tar_make(
  script = script,
  store = store
)
```

We visualise the pipeline:

```{r}
tar_visnetwork(
  script = script,
  store = store
)
```

## Visualise species richness

```{r}
tar_read(spatial_bird_richness, store = store)
```

## Challenge 2

```{r}
tar_read(top_species_presence, store = store)
```

## Challenge 3

Replace this target from the previous challenge

```r
tar_target(
  top_species_data,
  bird_cube_2020 |>
    dplyr::filter(species %in% top_species) |>
    dplyr::group_by(species) |>
    tar_group(),
  iteration = "group"
)
```

with

```r
tarchetypes::tar_group_by(
  top_species_data,
  bird_cube_2020 |>
    dplyr::filter(species %in% top_species),
  species
)
```
